SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF  EXISTS `tintuc`;
CREATE TABLE `tintuc`(
`id` int(20) unsigned NOT NULL AUTO_INCREMENT,
`tintuc_name` varchar(300) DEFAULT NULL,
`tintuc_menu` varchar(200) DEFAULT NULL,
`tintuc_content` text,
`tintuc_image` text,
PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT=138 DEFAULT CHARSET=utf8;
INSERT INTO `tintuc` VALUES ('1','Sài Gòn sau bão số 9: Phố đi bộ thành phố bơi lội, nhà dân hóa bể sinh vât cảnh đủ loại cá, gián và rắt rết','xã hội','Sau cơn bão số 9 đã qua nhưng những hậu quả mà nó để lại vẫn đang khiến người dân TP.HCM phải căng mình chống chọi','../image/baoso9.jpg');
INSERT INTO `tintuc` VALUES ('2','Những quán cafe và khu tổ hợp xinh xắn khiến bạn muốn bất chấp book vé Đà Nẵng ngay','đời sống','Đà Nẵng chưa bao giờ thiếu những không gian xinh xắn và lung linh đâu nhé','../image/cafevuon.jpg');
INSERT INTO `tintuc` VALUES ('3','Bạn có cảm thấy mình đang lãng phí tiềm năng của bản thân? Đừng lo, 7 kỹ năng sẽ giúp bạn khai thác hết những "khả năng tiềm tàng" của mình','đời sống','Đôi khi bạn có cảm thấy mình đang lãng phí tiềm năng của bản thân không? Và bạn cũng cảm thấy không chắc chắn rằng...','../image/tiemnang.jpg');
INSERT INTO `tintuc` VALUES ('4','Lịch sử AFF Cup ủng hộ Việt Nam: Philippines sở hữu thành tích toàn thua ở bán kết','sport','Philippines đã vào bán kết AFF Cup 2018 sau khi giành một điểm trong trận hòa không bàn thắng trước Indonesia tối qua(25/11). Trong lịch sử, đội bóng có biệt danh "The Azkals" sở hữu thành tích toàn thua ở bán kết AFF Cup','../image/philippin.jpg');
INSERT INTO `tintuc` VALUES ('5','Sau màn ra mắt ấn tượng tại Hà Nội, VinFast tiếp tục thu hét hàng ngàn người dân tới tham quan và đặt mua tại Sài Gòn','công nghệ','Cũng như Hà Nội, người Sài Gòn rất thích thú khi được chiêm ngưỡng 3 dòng xe ô tô, xe máy sang trọng của tập ...','../image/vinfast.jpg');
INSERT INTO `tintuc` VALUES ('6','Thương hiệu đồng hồ Franck Muller chính thức có mặt tại Việt Nam','fashion','Thương hiệu đồng hồ Franck Muller được thành lập bởi nghệ nhân Franck Muller cùng doanh nhân Vartan Sirmakes đã chính...','../image/dongho.jpg');
INSERT INTO `tintuc` VALUES ('7','Vườn cúc họa mi ở Hà Nội tiếp tục thất thủ: Đường vào tắc nghẽn ,chụp một bức ảnh...','đời sống',NULL ,'../image/images.jpg');
INSERT INTO `tintuc` VALUES ('8','Vườn cúc họa mi ở Hà Nội tiếp tục thất thủ: Đường vào tắc nghẽn ,chụp một bức ảnh...','đời sống',NULL,'../image/images.jpg');
INSERT INTO `tintuc` VALUES ('9','Vườn cúc họa mi ở Hà Nội tiếp tục thất thủ: Đường vào tắc nghẽn ,chụp một bức ảnh...','đời sống',NULL,'../image/images.jpg');
INSERT INTO `tintuc` VALUES ('10','Vườn cúc họa mi ở Hà Nội tiếp tục thất thủ: Đường vào tắc nghẽn ,chụp một bức ảnh...','đời sống',NULL,'../image/images.jpg');
INSERT INTO `tintuc` VALUES ('11','Vườn cúc họa mi ở Hà Nội tiếp tục thất thủ: Đường vào tắc nghẽn ,chụp một bức ảnh...','đời sống',NULL,'../image/images.jpg');
INSERT INTO `tintuc` VALUES ('12','Vườn cúc họa mi ở Hà Nội tiếp tục thất thủ: Đường vào tắc nghẽn ,chụp một bức ảnh...','đời sống',NULL,'../image/images.jpg');
INSERT INTO `tintuc` VALUES ('13','Vườn cúc họa mi ở Hà Nội tiếp tục thất thủ: Đường vào tắc nghẽn ,chụp một bức ảnh...','đời sống',NULL,'../image/images.jpg');
INSERT INTO `tintuc` VALUES ('14','Vườn cúc họa mi ở Hà Nội tiếp tục thất thủ: Đường vào tắc nghẽn ,chụp một bức ảnh...','đời sống',NULL,'../image/images.jpg');
INSERT INTO `tintuc` VALUES ('15','Thêm một tổ hợp ăn chơi, giải trí, mua sắm sầm uất thu hút giới trẻ tại Sài Gòn','cinema','Nhiều người thích shopping ở Quận 1 trung tâm nhưng ít ai biết được rằng, quận có số lượng siêu thị, trung tâm thương mại nhiều tại Sài Gòn lại là Gò Vấp','../image/govap.jpg');
INSERT INTO `tintuc` VALUES('16','Điểm vui chơi mới ở Sài Gòn: Công viên gải trí Just Kidding','cinema','Một khu vui chơi thu hút các bạn trẻ cùng gia đình với vai trog chơi ngoài troig khai trương ngày 1/12 tại Quận 12 mang đến nhiều màu sắc cho dịp cuối tuần','../image/kidding.jpg');
INSERT INTO `tintuc` VALUES('17','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','cinema',NULL,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('18','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','cinema',NULL,'../image/nhocty.jpg');
INSERT INTO `tintuc` VALUES('19','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','cinema',NULL ,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('20','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','cinema',NULL ,'../image/nhocty.jpg');
INSERT INTO `tintuc` VALUES('21','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','cinema',NULL ,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('22','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','cinema',NULL,'../image/nhocty.jpg');
INSERT INTO `tintuc` VALUES('23','Sprepark: Từng là công viên giải trí hàng đầu nước Đức, lụn bại sau khi rơi vào tay trùm thuốc phiện rồi bị bỏ hoang suốt 16 năm qua','cinema','Chẳng cần ra MV tiền tỷ, đóng phim bom tấn hay xuất hiện trong các show thời trang, những em bé này chỉ cần...','../image/congvienduc.jpg');
INSERT INTO `tintuc` VALUES('24','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','cinema','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','../image/bodauroi.jpg');
INSERT INTO `tintuc` VALUES('25','Khảo sát: 200 người trong ngành giải trí kpop bình chọn 3 ca khúc hay nhất 2018','cinema','Bảng khảo sát còn công bố 2 mục nữa là màn comeback được chào đón nhất và nghệ sĩ Kpop có bước ngoặt ấn tượng nhất...','../image/kpop.jpg');
INSERT INTO `tintuc` VALUES('26','Vsmart lộ diện gần như hoàn toàn trên website đại ly, chỉ chờ chốt giá bán chính thức','công nghệ','Có vẻ như mọi công đoạn chuẩn bị cho Vsmart sẵn sàng trước giờ G đã dần hoàn tất, dự kiến sẽ có 5000 điểm phân phối dành cho Vsmart.','../image/vsmart2.jpg');
INSERT INTO `tintuc` VALUES('27','Thủ phàm xịt ớt cay khiến 24 nhân viên Amazon nhập viện hóa ra là một robot "chập cheng"','công nghệ','Một con robot tại nhà kho cuaer Amazon đã xịt thuốc chống gấu khiến 24 công nhân phải nhập viện cấp cứu.','../image/xitcay.jpg');
INSERT INTO `tintuc` VALUES('28','Mừng thâm vì tưởng iphone Xs hạ giá 7 triệu cực mạnh, hóa ra chỉ là "cú lừa" từ Apple','công nghệ',NULL,'../image/xsmax.jpg');
INSERT INTO `tintuc` VALUES('29','Đời sống như mơ của thực tập sinh Facebook: Tự chọn giờ làm việc, lương lên gần 200 triệu/tháng','công nghệ',NULL,'../image/sinhviendilam.jpg');
INSERT INTO `tintuc` VALUES('30','Bất ngờ với mạng xã hội duy nhất lọt Top Google 2018, đá bay cả Facebook và Instagram','công nghệ',NULL ,'../image/tiktok.jpg');
INSERT INTO `tintuc` VALUES('31','Website của Vsmart lộ diện lúc nửa đêm: Sẽ bán ra toàn cầu, làm cả smartphone lẫn tai nghe, loa ngoài?','công nghệ',NULL ,'../image/vsmart3.jpg');
INSERT INTO `tintuc` VALUES('32','iphone bị cấm bán bởi toàn án Trung Quốc, theo sau vụ kiện trị giá hàng tỷ USD với Qualcomm','công nghệ',NULL,'../image/iphone.jpg');
INSERT INTO `tintuc` VALUES('33','Bật mí chiếc điện thoại cực thú vị gắn liền với trào lưu "Lite is good" gây bão trên TikTok','công nghệ',NULL,'../image/dttiktok.jpg');
INSERT INTO `tintuc` VALUES('34','Trung Quốc cái gì cũng làm được, kể cả phiên bản y hệt như robot chó SpotMini cuae Boston Dynamics','công nghệ','Các nhà khoa học tại Đại học Chiết Giang, Trung Quốc mới đây đã khoe một con robot bốn chan hình chó hoàn toàn mới. Thoạt nhìn, nhiều người có thể nhầm tưởng con robot này với robot cho Boston...','../image/chorobot.jpg');
INSERT INTO `tintuc` VALUES('35','Cỗ máy bước ra từ phim viễn tưởng, chụp ảnh ba chiều toàn bộ cơ thể người chỉ có 30 giây','công nghệ','Chúng có thể cho bác sĩ chuẩn đoán và theo dõi bệnh tật chính xác hơn bao giờ hết, chưa kể đến những lợi ích mà...','../image/comay3d.jpg');
INSERT INTO `tintuc` VALUES('36','Samsung ra mắt Galaxy A8s: Smartphone màn hình đục lỗ đầu tiên trên thế giới, 3 camera sau, chip Snapdragon 710, loại bỏ jack 3.5mm','công nghệ','Galaxy A8s là smartphone có màn hình đục lỗ đầu tiên trên thế giới được chính thức ra mắt','../image/samsunga8.jpg');
INSERT INTO `tintuc` VALUES('37','Điều gì khiến Đào Bá Lộc "phải lòng" thương hiệu Dickinson''s?Ký ức thanh xuân phải được lưu giữ bằng những chuyến đi!','đời sống','Nếu mỗi ngày trôi qua, bạn đều đang ru rú sau màn hình máy tính, đi về như một cái máy và lãng quên những chuyến ...','../image/daobaloc.jpg');
INSERT INTO `tintuc` VALUES('38','Năm nay ngoài 30 tuổi, tôi mới thản nhiên nói ra 6 điều từng khiến hầu hết chúng ta loay hoay, khổ sở năm 20 tuổi','đời sống','Có những lời cần có người nói ra, có những chuyện cần có người đi làm, không thì dựa vào đâu mà suốt ngày thấy người ...','../image/30tuoi.jpg');
INSERT INTO `tintuc` VALUES('39','Thiếu nữ gục ngã khi tốn tiền triệu làm xoăn nhẹ Hàn Quốc, kết quả lại ra giống "cây lau nhà di...','đời sống',NULL ,'../image/thieunu.jpg');
INSERT INTO `tintuc` VALUES('40','Thiếu nữ gục ngã khi tốn tiền triệu làm xoăn nhẹ Hàn Quốc, kết quả lại ra giống "cây lau nhà di...','đời sống',NULL ,'../image/thieunu.jpg');
INSERT INTO `tintuc` VALUES('41','Thiếu nữ gục ngã khi tốn tiền triệu làm xoăn nhẹ Hàn Quốc, kết quả lại ra giống "cây lau nhà di...','đời sống',NULL ,'../image/thieunu.jpg');
INSERT INTO `tintuc` VALUES('42','Thiếu nữ gục ngã khi tốn tiền triệu làm xoăn nhẹ Hàn Quốc, kết quả lại ra giống "cây lau nhà di...','đời sống',NULL ,'../image/thieunu.jpg');
INSERT INTO `tintuc` VALUES('43','Thiếu nữ gục ngã khi tốn tiền triệu làm xoăn nhẹ Hàn Quốc, kết quả lại ra giống "cây lau nhà di...','đời sống',NULL,'../image/thieunu.jpg');
INSERT INTO `tintuc` VALUES('44','Nếu trót sống lỗi cả năm, giờ là lúc học những tính cách "mượt mà" để xua bớt nghiệp quanh mình','đời sống','Nếu thấy hình ảnh của mình trong những bình luận dưới đây thì chắc chắn bạn đang hướng tói một hình anher hoa hậu thân...','../image/.jpg');
INSERT INTO `tintuc` VALUES('45','Loạt ảnh minh chứng: Một ekip hoành tráng chẳng bằng một đứa bạn chính ảnh có tâm','đời sống','Chẳng phải bổng nhiên mà con gái thích photoshop ảnh mình đến thế đâu, ai bảo photoshop lại "quyền năng" đến mức đổi...','../image/ekip.jpg');
INSERT INTO `tintuc` VALUES('46','Khổ như sinh viên đi làm: Kém hiểu biết nên lương thấp, thường xuyên bị bắt nạt, bóc lột','đời sống','Sinh viên đi làm thêm, đi thực tập, thử việc như làm dâu trăm họ vậy, may mắn thì gặp được công ty ngon lành, đối đãi...','../image/sinhviendilam.jpg');
INSERT INTO `tintuc` VALUES('47','Đà Lạt xuất hiện "ghế săn mây" để chụp ảnh sống ảo, không hổ danh là nơi đi hoàn chẳng chán','đời sống','"Cầu thang vô cực" ở Đà Lạt: Lên Instagram ảo bao nhiêu, ngoài đời phải chen lấn chụp ảnh mệt bấy nhiêu!','../image/dalat.jpg');
INSERT INTO `tintuc` VALUES('48','Điều gì khiến Đào Bá Lộc "phải lòng" thương hiệu Dickinson''s?','fashion','Không chỉ yêu mến giọng hát lạ, giàu cảm xúc...mới đây Đào Bá Lộc đã khiến chị em "chết mê" khi tung chiêu...','../image/daobaloc.jpg');
INSERT INTO `tintuc` VALUES('49','Giữa dàn cả trăm người đẹp, H.Hen Niê thuộc số hiếm đuọc chọn xuất hiện trên instagram của Vogue Thái với áo dài lạ','fashion','Và điều đặc biệt hơn cả chính là bộ trang phục mà H''Hen Niê đã lựa trong hoạt động mới mới đây tại Miss Universe 2018','../image/HHen.jpg');
INSERT INTO `tintuc` VALUES('50','5 cách đơn giản nhưng đảm bảo khiến tóc dày dặn, bồng bềnh hơn cho nàng nào tóc mỏng, tóc dễ xẹp','fashion','Trước khi tính đến chuyện nối tóc, bạn hãy thử áp dụng 5 cách làm dày tóc đơn giản nhưng lại hiệu quả và chẳng tốn...','../image/tocdaydan.jpg');
INSERT INTO `tintuc` VALUES('51','Một đôi boot đi liền suốt 4 tập The Face nhưng cái hay là ở mỗi tập Võ Hoàng Yến lại có cách mix đồ khác hẳn','fashion',NULL,'../image/boot4tap.jpg');
INSERT INTO `tintuc` VALUES ('52','Sài Gòn sau bão số 9: Phố đi bộ thành phố bơi lội, nhà dân hóa bể sinh vât cảnh đủ loại cá, gián và rắt rết','fashion','Sau cơn bão số 9 đã qua nhưng những hậu quả mà nó để lại vẫn đang khiến người dân TP.HCM phải căng mình chống chọi','../image/baoso9.jpg');
INSERT INTO `tintuc` VALUES ('53','Những quán cafe và khu tổ hợp xinh xắn khiến bạn muốn bất chấp book vé Đà Nẵng ngay','fashion','Đà Nẵng chưa bao giờ thiếu những không gian xinh xắn và lung linh đâu nhé','../image/cafevuon.jpg');
INSERT INTO `tintuc` VALUES ('54','Bạn có cảm thấy mình đang lãng phí tiềm năng của bản thân? Đừng lo, 7 kỹ năng sẽ giúp bạn khai thác hết những "khả năng tiềm tàng" của mình','fashion','Đôi khi bạn có cảm thấy mình đang lãng phí tiềm năng của bản thân không? Và bạn cũng cảm thấy không chắc chắn rằng...','../image/tiemnang.jpg');
INSERT INTO `tintuc` VALUES('55','Một đôi boot đi liền suốt 4 tập The Face nhưng cái hay là ở mỗi tập Võ Hoàng Yến lại có cách mix đồ khác hẳn','fashion',NULL,'../image/boot4tap.jpg');
INSERT INTO `tintuc` VALUES('56','Có giá từ 400k, đây là 8 loại serum "đỉnh của đỉnh" dành cho da mụn được các bác sĩ da liễu  khuyên dùng nhiều nhất','fashion','Từ đặc trị mụn cho đến dưỡng ẩm phù hợp với da mun, đây là 8 ứng cử viên serum được các bác sĩ da liễu tại Mỹ đặc biệt tín ...','../image/8mypham.jpg');
INSERT INTO `tintuc` VALUES('57','BST Thu Đông giày Superga 2750: khi thời trang là bước chân tự do','fashion','Những cơn gió mang hơi thở của thời trang Thu Đông 2018 đã tràn về và hiện diện ở khắp mọi nơi. Không khí lễ hội tưng...','../image/BST.jpg');
INSERT INTO `tintuc` VALUES('58','Thêm một tổ hợp ăn chơi, giải trí, mua sắm sầm uất thu hút giới trẻ tại Sài Gòn','giải trí','Nhiều người thích shopping ở Quận 1 trung tâm nhưng ít ai biết được rằng, quận có số lượng siêu thị, trung tâm thương mại nhiều tại Sài Gòn lại là Gò Vấp','../image/govap.jpg');
INSERT INTO `tintuc` VALUES('59','Điểm vui chơi mới ở Sài Gòn: Công viên gải trí Just Kidding','giải trí','Một khu vui chơi thu hút các bạn trẻ cùng gia đình với vai trong chơi ngoài  khai trương ngày 1/12 tại Quận 12 mang đến nhiều màu sắc cho dịp cuối tuần','../image/kidding.jpg');
INSERT INTO `tintuc` VALUES('60','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','giải trí',NULL,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('61','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','giải trí',NULL ,'../image/nhocty.jpg');
INSERT INTO `tintuc` VALUES('62','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','giải trí',NULL ,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('63','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','giải trí',NULL ,'../image/nhocty.jpg');
INSERT INTO `tintuc` VALUES('64','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','giải trí',NULL ,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('65','Sprepark: Từng là công viên giải trí hàng đầu nước Đức, lụn bại sau khi rơi vào tay trùm thuốc phiện rồi bị bỏ hoang suốt 16 năm qua','giải trí','Sprepark: Từng là công viên giải trí hàng đầu nước Đức, lụn bại sau khi rơi vào tay trùm thuốc phiện rồi bị bỏ hoang...','../image/congvienduc.jpg');
INSERT INTO `tintuc` VALUES('66','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','giải trí','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','../image/bodauroi.jpg');
INSERT INTO `tintuc` VALUES('67','Khảo sát: 200 người trong ngành giải trí kpop bình chọn 3 ca khúc hay nhất 2018','giải trí','Khảo sát: 200 người trong ngành giải trí kpop bình chọn 3 ca khúc hay nhất 2018','../image/kpop.jpg');
INSERT INTO `tintuc` VALUES('68','Thêm một tổ hợp ăn chơi, giải trí, mua sắm sầm uất thu hút giới trẻ tại Sài Gòn','học đường','Nhiều người thích shopping ở Quận 1 trung tâm nhưng ít ai biết được rằng, quận có số lượng siêu thị, trung tâm thương mại nhiều tại Sài Gòn lại là Gò Vấp','../image/govap.jpg');
INSERT INTO `tintuc` VALUES('69','Điểm vui chơi mới ở Sài Gòn: Công viên gải trí Just Kidding','học đường','Một khu vui chơi thu hút các bạn trẻ cùng gia đình với vai trong chơi ngoài  khai trương ngày 1/12 tại Quận 12 mang đến nhiều màu sắc cho dịp cuối tuần','../image/kidding.jpg');
INSERT INTO `tintuc` VALUES('70','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','học đường',NULL,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('71','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','học đường',NULL ,'../image/nhocty.jpg');
INSERT INTO `tintuc` VALUES('72','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','học đường',NULL ,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('73','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','học đường',NULL ,'../image/nhocty.jpg');
INSERT INTO `tintuc` VALUES('74','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','học đường',NULL ,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('75','Sprepark: Từng là công viên giải trí hàng đầu nước Đức, lụn bại sau khi rơi vào tay trùm thuốc phiện rồi bị bỏ hoang suốt 16 năm qua','học đường','Sprepark: Từng là công viên giải trí hàng đầu nước Đức, lụn bại sau khi rơi vào tay trùm thuốc phiện rồi bị bỏ hoang...','../image/congvienduc.jpg');
INSERT INTO `tintuc` VALUES('76','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','học đường','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','../image/bodauroi.jpg');
INSERT INTO `tintuc` VALUES('77','Khảo sát: 200 người trong ngành giải trí kpop bình chọn 3 ca khúc hay nhất 2018','học đường','Khảo sát: 200 người trong ngành giải trí kpop bình chọn 3 ca khúc hay nhất 2018','../image/kpop.jpg');
INSERT INTO `tintuc` VALUES('78','Thêm một tổ hợp ăn chơi, giải trí, mua sắm sầm uất thu hút giới trẻ tại Sài Gòn','kinh doanh','Nhiều người thích shopping ở Quận 1 trung tâm nhưng ít ai biết được rằng, quận có số lượng siêu thị, trung tâm thương mại nhiều tại Sài Gòn lại là Gò Vấp','../image/govap.jpg');
INSERT INTO `tintuc` VALUES('79','Điểm vui chơi mới ở Sài Gòn: Công viên gải trí Just Kidding','kinh doanh','Một khu vui chơi thu hút các bạn trẻ cùng gia đình với vai trong chơi ngoài  khai trương ngày 1/12 tại Quận 12 mang đến nhiều màu sắc cho dịp cuối tuần','../image/kidding.jpg');
INSERT INTO `tintuc` VALUES('80','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','kinh doanh',NULL,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('81','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','kinh doanh',NULL ,'../image/nhocty.jpg');
INSERT INTO `tintuc` VALUES('82','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','kinh doanh',NULL ,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('83','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','kinh doanh',NULL ,'../image/nhocty.jpg');
INSERT INTO `tintuc` VALUES('84','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','kinh doanh',NULL ,'../image/flamingo.jpg');
INSERT INTO `tintuc` VALUES('85','Sprepark: Từng là công viên giải trí hàng đầu nước Đức, lụn bại sau khi rơi vào tay trùm thuốc phiện rồi bị bỏ hoang suốt 16 năm qua','kinh doanh','Sprepark: Từng là công viên giải trí hàng đầu nước Đức, lụn bại sau khi rơi vào tay trùm thuốc phiện rồi bị bỏ hoang...','../image/cuchoami.jpg');
INSERT INTO `tintuc` VALUES('86','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','kinh doanh','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','../image/h9.jpg');
INSERT INTO `tintuc` VALUES('87','Khảo sát: 200 người trong ngành giải trí kpop bình chọn 3 ca khúc hay nhất 2018','kinh doanh','Khảo sát: 200 người trong ngành giải trí kpop bình chọn 3 ca khúc hay nhất 2018','../image/h9.jpg');
INSERT INTO `tintuc` VALUES('88','Thêm một tổ hợp ăn chơi, giải trí, mua sắm sầm uất thu hút giới trẻ tại Sài Gòn','music','Nhiều người thích shopping ở Quận 1 trung tâm nhưng ít ai biết được rằng, quận có số lượng siêu thị, trung tâm thương mại nhiều tại Sài Gòn lại là Gò Vấp','../image/cuchoami.jpg');
INSERT INTO `tintuc` VALUES('89','Điểm vui chơi mới ở Sài Gòn: Công viên gải trí Just Kidding','music','Một khu vui chơi thu hút các bạn trẻ cùng gia đình với vai trong chơi ngoài  khai trương ngày 1/12 tại Quận 12 mang đến nhiều màu sắc cho dịp cuối tuần','../image/cuchoami.jpg');
INSERT INTO `tintuc` VALUES('90','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','music',NULL,'../image/h9.jpg');
INSERT INTO `tintuc` VALUES('91','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','music',NULL ,'../image/cuchoami.jpg');
INSERT INTO `tintuc` VALUES('92','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','music',NULL ,'../image/h9.jpg');
INSERT INTO `tintuc` VALUES('93','Ngắm loạt nhóc tỳ đang hot nhất MXH: Nếu không quá đáng yêu thì cũng là meme đậm chất giải trí','music',NULL ,'../image/cuchoami.jpg');
INSERT INTO `tintuc` VALUES('94','Có gì hot tại thế giới giải trí bất tận Flamingo Play World?','music',NULL ,'../image/h9.jpg');
INSERT INTO `tintuc` VALUES('95','Sprepark: Từng là công viên giải trí hàng đầu nước Đức, lụn bại sau khi rơi vào tay trùm thuốc phiện rồi bị bỏ hoang suốt 16 năm qua','music','Sprepark: Từng là công viên giải trí hàng đầu nước Đức, lụn bại sau khi rơi vào tay trùm thuốc phiện rồi bị bỏ hoang...','../image/congvienduc.jpg');
INSERT INTO `tintuc` VALUES('96','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','music','Phim giải trí gia đình "Mẹ Ơi, Bố Đâu Mất Rồi" gây hiện tượng ngay tập đầu tiên','../image/bodauroi.jpg');
INSERT INTO `tintuc` VALUES('97','Khảo sát: 200 người trong ngành giải trí kpop bình chọn 3 ca khúc hay nhất 2018','music','Khảo sát: 200 người trong ngành giải trí kpop bình chọn 3 ca khúc hay nhất 2018','../image/kpop.jpg');
INSERT INTO `tintuc` VALUES('98','Tỷ số nào ở trận lượt về sẽ giúp Đt Việt Nam vô địch AFF Cup 2018?','sport','Ghi 2 bàn trên sân khách, thầy trò HLV Park Hang-seo nắm lợi thế không nhỏ trước trận lượt về chung kết AFF Cup 2018.','../image/tyso.jpg');
INSERT INTO `tintuc` VALUES('99','Đội trưởng tuyển Việt Nam tin tưởng sẽ vô địch AFF Cup 2018','sport','Mặc dù không thể giữu vững lượi thế dẫn bàn trong trận chung kết lượt đi AFF Cup 2018, trung vệ Quế Ngọc Hải vẫn tự tin..','../image/doitruong.jpg');
INSERT INTO `tintuc` VALUES('100','Bỏ hàng chục triệu sang Malaysia, CĐV Việt Nam vẫn phải ngồi chen chúc, chênh vênh trên khán đài','sport','Để tận hưởng bầu không khí tại BUkit Jalil và cổ vũ đội tuyển con cưng, rất nhiều fan Việt Nam đã phải đứng, chen chúc...','../image/chenchuc.jpg');
INSERT INTO `tintuc` VALUES('101','Bố mẹ Đình Trọng xót xa khi con trai bị phạm lỗi liên tiếp trong trận chung kết AFF Cup 2018','sport','"Nổi da gà" với sức nóng của chảo lửa Bukit Jalil','../image/bodinhtrong.jpg');
INSERT INTO `tintuc` VALUES('102','Nước rút thần tốc, không hoãn trận chung kết AFF Cup 2018 Malaysia đấu Việt Nam','sport','Những lo ngại về vấn đề thời tiết đã tạm thời trôi qua, trận chung kết AFF Cup giữa Malaysia và Việt Nam sẽ diễn ra...','../image/nuocrut.jpg');
INSERT INTO `tintuc` VALUES('103','Trưởng nhóm cổ động viên Việt Nam phủ nhận thông tin fan Việt bị đánh tại Malaysia trước thêm chung kết lượt đi AFF Cup','sport','Cổ động viên Việt Nam hãy coi chừng Ultras Malaysia','../image/codong.jpg');
INSERT INTO `tintuc` VALUES('104','Bỏ hàng chục triệu sang Malaysia, CĐV Việt Nam vẫn phải ngồi chen chúc, chênh vênh trên khán đài','sport','Để tận hưởng bầu không khí tại BUkit Jalil và cổ vũ đội tuyển con cưng, rất nhiều fan Việt Nam đã phải đứng, chen chúc...','../image/cuchoami.jpg');
INSERT INTO `tintuc` VALUES('105','Bố mẹ Đình Trọng xót xa khi con trai bị phạm lỗi liên tiếp trong trận chung kết AFF Cup 2018','sport','"Nổi da gà" với sức nóng của chảo lửa Bukit Jalil','../image/bodinhtrong.jpg');
INSERT INTO `tintuc` VALUES('106','Nước rút thần tốc, không hoãn trận chung kết AFF Cup 2018 Malaysia đấu Việt Nam','sport','Những lo ngại về vấn đề thời tiết đã tạm thời trôi qua, trận chung kết AFF Cup giữa Malaysia và Việt Nam sẽ diễn ra...','../image/nuocrut.jpg');
INSERT INTO `tintuc` VALUES('107','Trưởng nhóm cổ động viên Việt Nam phủ nhận thông tin fan Việt bị đánh tại Malaysia trước thêm chung kết lượt đi AFF Cup','sport','Cổ động viên Việt Nam hãy coi chừng Ultras Malaysia','../image/codong.jpg');
INSERT INTO `tintuc` VALUES('108','Bố mẹ Lý Dịch Phong thời trẻ: Trai xinh gái đẹp thế này bảo sao con trai ưu tú đến thế!','star','Lý Dịch Phong vừa biến bố mẹ mình trở thành tâm điểm chú ý của dân tình khi khoe bức ảnh thời trẻ của họ.','../image/bm.jpg');
INSERT INTO `tintuc` VALUES('109','Thêm bằng chứng tố Phương Khánh mua giải Miss Earth 2018, thẩm mỹ và hẹn hò bác sĩ Chiêm Quốc Thái','star','Liên tiếp những ngày gần đây, hàng loạt thông tin về việc Phương Khánh vô ơn với người dìu dắt, mua giả Miss Earth...','../image/pkhanh.jpg');
INSERT INTO `tintuc` VALUES('110','Brooklyn vừa già trước tuổi vừa nhạt nhòa khi đứng cạnh bố Beckham quá điển trai trên thảm đỏ','star',NULL,'../image/bkham.jpg');
INSERT INTO `tintuc` VALUES('111','Jun Vũ: "Hay là nên làm miitj Hoa hậu ngoan hiền, nhưng như thế có phải tôi tự đánh mất luôn bản thân mình không?"','star',NULL ,'../image/jun.jpg');
INSERT INTO `tintuc` VALUES('112','Brooklyn vừa già trước tuổi vừa nhạt nhòa khi đứng cạnh bố Beckham quá điển trai trên thảm đỏ','star',NULL ,'../image/bkham.jpg');
INSERT INTO `tintuc` VALUES('113','Jun Vũ: "Hay là nên làm miitj Hoa hậu ngoan hiền, nhưng như thế có phải tôi tự đánh mất luôn bản thân mình không?"','star',NULL ,'../image/jun.jpg');
INSERT INTO `tintuc` VALUES('114','Brooklyn vừa già trước tuổi vừa nhạt nhòa khi đứng cạnh bố Beckham quá điển trai trên thảm đỏ','star',NULL ,'../image/bkham.jpg');
INSERT INTO `tintuc` VALUES('115','Nhờ cú bấm "follow" của thiếu gia Vương Tư Thông, mỹ nhân đẹp hoàn hảo đến "bức người" này trở thành hiện tượng MXH','star','Chương Nhược Nam - mỹ nhân hot nhất mạng xã hội xứ Trung thời điểm hiện tại nhờ được thiếu gia Vương Tư Thông chú ý và...','../image/vtt.jpg');
INSERT INTO `tintuc` VALUES('116','Nhiều tháng ở nhà chăm con, Hoắc Kiến Hoa chia sẻ mình bị "rối loạn ám ảnh cưỡng chế"','star','Lâm Tâm Như cũng tiết lộ, khi ở nhà, Hoắc Kiến Hoa cứ vài phút phải ngó nghiêng con gái 1 lần mới cảm thấy an tâm được.','../image/hkh.jpg');
INSERT INTO `tintuc` VALUES('117','Tình bạn trong các nhóm nhạc Kpop đình đám: Càng đấu đá nhau quyết liệt, càng thân đến khó tin"','star','Trong khi fan còn đang khẩu chiến gay gắt, thần tượng trong các nhóm nhạc kpop đình đám như Big Bang, Super Junior...','../image/pop.jpg');
INSERT INTO `tintuc` VALUES('118','Bước sang độ tuổi U30, Park Shin Hye mới đạt đến đẳng cấp nhan sắc rực rỡ nhất','star','Không được đánh giá cao từ lâu, Park Shin Hye chứng minh đẳng cấp nhan sắc chỉ bằng vài bức ảnh hậu trường','../image/u30.jpg');
INSERT INTO `tintuc` VALUES('119','"Chị đẹp" Son Ye Jin đóng phim không ngừng nghỉ suốt 20 năm vì sợ có ai đó vượt qua mình','tv show','Son Ye Jin đã có những chia sẻ về nghề nghiệp khi làm khách mời trong show thực tế.','../image/chidep.jpg');
INSERT INTO `tintuc` VALUES('120','Cứ nói Jennie được YG "thiên vị" nhưng đây mới là thành viên dược đi show nhiều nhất BLACKPINK!','tv show',NULL,'../image/jennie.jpg');
INSERT INTO `tintuc` VALUES('121','Sự thật việc Hari Won bị đồn thổi bỏ dẫn show thực tế vì bất đồng với Trường Giang','tv show',NULL ,'../image/hari.jpg');
INSERT INTO `tintuc` VALUES('122','Người đẹp "vượt mặt" Tiểu Vy giành vương miện Miss World 2018 chính là Quán quân "Next Top Mexico"','tv show',NULL ,'../image/vuotmat tieuvy.jpg');
INSERT INTO `tintuc` VALUES('123','Trấn Thành biết ơn Tiến Đạt vì đã từng tốt với Hari Won','tv show',NULL ,'../image/tranthanh.jpg');
INSERT INTO `tintuc` VALUES('124','Số phận bi thảm của các cựu thí sinh "Next Top Mỹ": Người qua đời vì bệnh tật, kể bị sát hại','tv show',NULL,'../image/bitham.jpg');
INSERT INTO `tintuc` VALUES('125','Hani (EXID) hoảng sợ bỏ chạy, cởi cả áo khoác vì bị ném... rắn giả vào người','tv show','Các fan của hani đã "không còn quần để đội" nữ rồi!','../image/hani.jpg');
INSERT INTO `tintuc` VALUES('126','"Fan girl" chính hiệu là đây: Mẹ của thực tập sinh nhà YG òa khóc nức nở khi gặp Seungri (Big Bang)','tv show','Giọt nước mắt "fan girl" lướn tuổi khiến Seungri cũng phải bối rối','../image/fangirl.jpg');
INSERT INTO `tintuc` VALUES('127','Sasuke Việt Nam tập 15: Con số 88 mang lại may mắn cho 5 thí sinh','tv show','Bất ngờ chia sẻ mình sinh năm 88 có lẽ mang lại may mắn cho các thí sinh trong phần thi hôm nay, MC Hà Trinh được MC...','../image/sasuke.jpg');
INSERT INTO `tintuc` VALUES('128','Tỷ số nào ở trận lượt về sẽ giúp Đt Việt Nam vô địch AFF Cup 2018?','xã hội','Ghi 2 bàn trên sân khách, thầy trò HLV Park Hang-seo nắm lợi thể không nhỏ trước trận lượt về chung kết AFF Cup 2018.','../image/tyso.jpg');
INSERT INTO `tintuc` VALUES('129','Đội trưởng tuyển Việt Nam tin tưởng sẽ vô địch AFF Cup 2018','xã hội','Mặc dù không thể giữu vững lượi thế dẫn bàn trong trận chung kết lượt đi AFF Cup 2018, trung vệ Quế Ngọc Hải vẫn tự tin..','../image/h9.jpg');
INSERT INTO `tintuc` VALUES('130','Bỏ hàng chục triệu sang Malaysia, CĐV Việt Nam vẫn phải ngồi chen chúc, chênh vênh trên khán đài','xã hội','Để tận hưởng bầu không khí tại BUkit Jalil và cổ vũ đội tuyển con cưng, rất nhiều fan Việt Nam đã phải đứng, chen chúc...','../image/chenchuc.jpg');
INSERT INTO `tintuc` VALUES('131','Bố mẹ Đình Trọng xót xa khi con trai bị phạm lỗi liên tiếp trong trận chung kết AFF Cup 2018','xã hội','"Nổi da gà" với sức nóng của chảo lửa Bukit Jalil','../image/bodinhtrong.jpg');
INSERT INTO `tintuc` VALUES('132','Nước rút thần tốc, không hoãn trận chung kết AFF Cup 2018 Malaysia đấu Việt Nam','xã hội','Những lo ngại về vấn đề thời tiết đã tạm thời trôi qua, trận chung kết AFF Cup giữa Malaysia và Việt Nam sẽ diễn ra...','../image/nuocrut.jpg');
INSERT INTO `tintuc` VALUES('133','Trưởng nhóm cổ động viên Việt Nam phủ nhận thông tin fan Việt bị đánh tại Malaysia trước thêm chung kết lượt đi AFF Cup','xã hội','Cổ động viên Việt Nam hãy coi chừng Ultras Malaysia','../image/codong.jpg');
INSERT INTO `tintuc` VALUES('134','Bỏ hàng chục triệu sang Malaysia, CĐV Việt Nam vẫn phải ngồi chen chúc, chênh vênh trên khán đài','xã hội','Để tận hưởng bầu không khí tại BUkit Jalil và cổ vũ đội tuyển con cưng, rất nhiều fan Việt Nam đã phải đứng, chen chúc...','../image/chenchuc.jpg');
INSERT INTO `tintuc` VALUES('135','Bố mẹ Đình Trọng xót xa khi con trai bị phạm lỗi liên tiếp trong trận chung kết AFF Cup 2018','xã hội','"Nổi da gà" với sức nóng của chảo lửa Bukit Jalil','../image/bodinhtrong.jpg');
INSERT INTO `tintuc` VALUES('136','Nước rút thần tốc, không hoãn trận chung kết AFF Cup 2018 Malaysia đấu Việt Nam','xã hội','Những lo ngại về vấn đề thời tiết đã tạm thời trôi qua, trận chung kết AFF Cup giữa Malaysia và Việt Nam sẽ diễn ra...','../image/nuocrut.jpg');
INSERT INTO `tintuc` VALUES('137','Trưởng nhóm cổ động viên Việt Nam phủ nhận thông tin fan Việt bị đánh tại Malaysia trước thêm chung kết lượt đi AFF Cup','xã hội','Cổ động viên Việt Nam hãy coi chừng Ultras Malaysia','../image/codong.jpg');
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF  EXISTS `thongtin`;
CREATE TABLE `thongtin`(
`thongtin_id` int(20) unsigned NOT NULL AUTO_INCREMENT,
`id` int(20),
`thongtin_name` text ,
`tieude_content` text,
`thongtin_span` text,
`content_p` varchar(100),
`diachi` varchar(200),
`ul_li` varchar(200),
`STT` varchar(50),
`thongtin_content` text,
`thongtin_image` text,
`chuthich` text,
PRIMARY KEY (`thongtin_id`)
) ENGINE = InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;
INSERT INTO `thongtin` VALUES('1','1','Sài Gòn sau bão số 9: Phố đi bộ thành phố bơi lội, nhà dân hoá bể sinh vật cảnh với đủ loại cá, gián và rắn rết','Cơn bão số 9 đã đi qua nhưng những hậu quả mà nó để lại vẫn đang khiến người dân TP HCM phải căng mình chống chọi, thích nghi và khắc phục.','TRỊNH THÚI,','THEO NHỊP SỐNG SG',NULL,'Sài Gòn ngập nặng nhiều tuyến đường sau bão số 9, dân công sở chật vật lội nước đi làm sáng đầu tuần',NULL,'Cơn bão số 9 mang tên Usagi đã đi qua nhưng những hậu quả mà nó để lại vẫn đang khiến người dân Sài Gòn phải căng mình chống chọi, thích nghi. Mưa lớn kéo dài gây ngập lụt trên nhiều tuyến phố tại khu vực trung tâm khiến đời sống sinh hoạt của người dân bị ảnh hưởng nghiêm trọng.Giao thông tê liệt, hàng loạt phương tiện chết máy do nước tràn vào nằm ngổn ngang khắp các ngõ phố. Lúc này, đi bộ chính là cách di chuyển tiện lợi nhất, còn nếu muốn khô ráo có lẽ chỉ có dùng xuồng! Thêm nữa, nước dâng cao tràn vào nhà dân cũng kéo theo không ít "vị khách không mời" tới tá túc khiến người dân phải vất vả dọn dẹp.Dưới đây là một số hình ảnh, clip vừa được cư dân mạng Sài Thành chia sẻ cho thấy thực trạng của thành phố sau bão số 9: Phố đi bộ biến thành phố bơi lội, trong khi nhà dân hoá thành... bể sinh vật cảnh với đủ loại cá cho tới gián và rắn rết!','../../image/SG1.jpg',NULL);
INSERT INTO `thongtin` VALUES('2','1',NULL,NULL,NULL,NULL,NULL,'Dân Sài Gòn đồng loạt chia sẻ ảnh và clip "chống bão, lội ngập" trong trận mưa như trút cả ngày vì bão số 9',NULL,'Bão đã khổ nhưng sau bão có khi còn vất vả hơn bởi những nguy cơ bệnh dịch tiềm ẩn do dòng nước kéo theo nhiều rác rưởi gây mất vệ sinh. Cũng chính trong thời điểm khó khăn này, người dân Sài Gòn đang chứng minh cho cả nước thấy họ là những người vô cùng lạc quan khi tập trung khắc phục hậu quả một cách vui vẻ và tích cực.','../../SG2.jpg','Một con rắn được phát hiện ngay trong nhà dân trong cơn ngập lụt!');
INSERT INTO `thongtin` VALUES('3','1',NULL,NULL,NULL,NULL,NULL,'TPHCM cắt điện hơn 60.000 khách hàng để đảm bảo an toàn trong cơn bão số 9',NULL,NULL,'../../SG3.jpg','Nếu không muốn đi bộ hay bơi lội thì chỉ còn cách là đóng bè! (Ảnh Nguyễn Thái Trường Dung)');
INSERT INTO `thongtin` VALUES('4','2','Những quán cà phê và khu tổ hợp xinh xắn khiến bạn muốn bất chấp book vé đi Đà Nẵng ngay','Đà Nẵng chưa bao giờ thiếu những không gian xinh xắn và lung linh đâu nhé!','N.N',' THEO NHỊP SỐNG DN','Địa chỉ: Lô 419 - 422 Ngô Thì Sĩ, phường Mỹ An, quận Ngũ Hành Sơn <br>Thời gian mở cửa: 7h - 22h<br>Mức giá: 30 - 70k','Hội bạn thân Đà Nẵng: 5 cô gái từng bị người yêu phản bội, gạt đau khổ để ngày càng đẹp!','1. 43 Factory Coffee','Mỗi người đến với Đà Nẵng đều sẽ "cảm nắng" thành phố này vì nhiều lí do khác nhau. Người thì mê tít mù ẩm thực miền trung, người lại thích thú với nhịp sống rộn ràng nhưng không quá đông đúc, ồn ào của Đà thành.  Gần đây, Đà Nẵng có thêm lí do để người ta muốn book vé đến đây ngay lập tức. Đó là những quán cà phê mới toanh cực kì xinh xắn hay 1 khu tổ hợp có đủ tất tần tật không thiếu thứ gì. Càng ngày, không gian dành cho giới trẻ ở thành phố này càng lung linh và xinh xắn chẳng kém gì Sài Gòn hay Hà Nội..','../../image/factory.jpg','Quán có không gian cực kì rộng rãi, thoáng đãng (@elledecorationvn)');
INSERT INTO `thongtin` VALUES('5','2',NULL,NULL,NULL,NULL,NULL,'Hội trai xinh gái đẹp mới toanh với clip check-in Đà Nẵng cực hot trên TikTok',NULL,NULL,'../image/factory1.jpg','Không gian ngập tràn ánh sáng tự nhiên (@maimai173)');
INSERT INTO `thongtin` VALUES('6','2',NULL,NULL,NULL,NULL,'Địa chỉ: 287 Nguyễn Chí Thanh, phường Phước Ninh, quận Hải Châu<br>Thời gian mở cửa: 7 - 22h<br>Mức giá: 15 - 40k','Khu tổ hợp dành cho giới trẻ đầu tiên ở Đà Nẵng: Rộng 1200m2, có đầy đủ từ tiệm cà phê đến homestay đẹp miễn bàn','2. Grand.T Coffee','Thêm một quán cà phê mới toanh rất thích hợp để bạn lê la trong những ngày cuối tuần. Grand.T không nằm ở vị trí quá đắc địa nên chưa được biết đến nhiều. Vì vậy, quán không quá đông đúc và ồn ào','../../image/grand.jpg','(@_tuctucc)');
INSERT INTO `thongtin` VALUES('7','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'../../image/grand1.jpg','(@maimai173)');
INSERT INTO `thongtin` VALUES('8','2',NULL,NULL,NULL,NULL,'Địa chỉ: 38 Pasteur, quận Hải Châu <br>Thời gian mở cửa: 8-22h',NULL,'3. Khu tổ hợp Zone Đà Nẵng',NULL,'../../image/zone.png','Đây là khu tổ hợp cho giới trẻ đầu tiên ở Đà Nẵng');
INSERT INTO `thongtin` VALUES('9','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'../../image/zone1.jpg','Không gian rất trẻ trung');
INSERT INTO `thongtin` VALUES('10','3','Bạn có cảm thấy mình đang lãng phí tiềm năng của bản thân? Đừng lo, 7 kỹ năng sẽ giúp bạn khai thác hết những "khare năng tiềm tàng" của mình','Đôi khi bạn có cảm thấy mình đang lãng phí tiềm năng của bản thân không? Và bạn cũng cảm thấy không chắc chắn rằng bạn có thể đạt được hết tiềm năng của mình?','TRỊNH THƠM,','THEO NHỊP SỐNG KINH TẾ/MEDIUM',NULL,'Đừng để áp lực công việc khiến bạn gục ngã, đây là cách những người bận rộn trên thế giới tái tạo năng lượng để "sống hòa bình" với thứ khó nhằn nhất',NULL,'Đôi khi bạn có cảm thấy mình đang lãng phí tiềm năng của bản thân không? Và cũng cảm thấy không chắc chắn rằng bạn có thể đạt được hết tiềm năng của mình?<br>Nếu vậy, bạn giống như bất kỳ một người có tham vọng nào khác muốn tận dụng tối đa cuộc sống của mình, cũng có nghĩa là bạn đang muốn "đạt được hết tiềm năng của bản thân".<br>Tất cả chúng ta đều biết rằng thời gian là vô hạn, nhưng thời gian trên tay chúng ta lại có giới hạn. Sẽ có một số người sống lâu hơn những người khác. Nhưng tất cả chúng ta đều biết rằng vấn đề không phải là bạn sống được bao lâu, mà vấn đề là bạn làm được những gì khi bạn còn sống.<br>Khi đuổi theo những mục tiêu vô nghĩa, bạn sẽ cảm thấy bồn chồn và trống rỗng. Thay vào đó, hãy theo đuổi tiềm năng của chính bạn và quên đi những thứ bên ngoài. Hãy trở thành một người tốt nhất bạn có thể. Đó là mục tiêu đáng theo đuổi duy nhất ở đây. Những người nổi tiếng như Muhammad Ali, Helen Keller, Thomas Edison hay Malcolm X, họ đều sống để theo đuổi khả năng tiềm tàng của mình, để tạo ra những tác động đến thế giới này.<br>Vậy phải làm thế nào để chúng ta có thể khai thác được hết tiềm năng của mình? Mất bao lâu để chúng ta làm điều đó? Dưới đây là 7 kỹ năng mà hầu như tất cả những người tuyệt vời này đều có điểm chung và tận dụng được tối đa tiềm lực của bản thân.','../../image/langphi.jpg',NULL);
INSERT INTO `thongtin` VALUES('11','3',NULL,NULL,NULL,NULL,NULL,'Cách chắc chắn khiến chúng ta điên loạn là nhúng tay vào việc của nguowig khác, muốn sống hạnh phúc chỉ cần tập trung vào chuyện của mình','1. Tự nhận thức','Bạn cần thoải mái với việc bạn là ai và bạn sẽ như thế nào. Đừng cố làm điều gì đó mà bản thân không muốn làm. Và đừng cố thay đổi bản thân chỉ vì những người khác bảo bạn như thế. Thay vào đó, biết bạn là ai. Nếu bạn không biết, hãy tìm hiểu. Đọc, viết, suy nghĩ, nói chuyện... Đó là sự tự nhận thức: Nó đòi hỏi bạn phải ý thức được suy nghĩ của mình.<br>Khi bạn tự nhận thức, bạn sẽ tự động tìm hiểu thêm về bản thân bạn. Khi bạn đã hiểu rõ được bản thân mình, những việc khác sẽ trở nên dễ dàng hơn rất nhiều.',NULL,NULL );
INSERT INTO `thongtin` VALUES('12','3',NULL,NULL,NULL,NULL,NULL,'Clip: Đỉnh cao của một con người chính là ngay cả khi một mình, vẫn có thể tận hưởng cuộc sống một cách trọn vẹn nhất','2.Lãnh đạo','Đầu tiên, hãy tập trung vào bản thân. Khắc phục nhược điểm của riêng bạn. Trở thành một người ổn định mà chính bạn có thể dựa vào trước đã. Một khi bạn đã làm được điều đó, hãy truyền cảm hứng cho những người khác làm như vậy. Các nhà lãnh đạo giỏi phải dạy người khác biết độc lập. Làm thế nào? Không có cách nào tốt hơn là dẫn dắt họ.<br>Nhưng: "Đừng cho người ta con cá vì họ có thể ăn hết mà không biết lấy từ đâu nữa, hãy dạy người ta cách bắt cá để họ có thể ăn bất cứ lúc nào họ muốn". Cách tốt nhất để giúp đỡ người khác là dạy họ dựa vào chính họ, và đó là cái hay của người có tố chất làm nhà lãnh đạo.',NULL,NULL );
INSERT INTO `thongtin` VALUES('13','3',NULL,NULL,NULL,NULL,NULL,NULL,'3.Viết','Khả năng viết tốt dẫn đến suy nghĩ tốt hơn. Suy nghĩ tốt hơn dẫn đến giao tiếp tốt hơn. Và tất nhiên, giao tiếp tốt hơn dẫn đến kết quả tốt hơn trong sự nghiệp của bạn. Khi bạn làm tốt ở một thứ, nó sẽ giúp bạn có nền tảng để làm tốt hơn ở những thứ khác.<br>Đôi khi mọi thứ sẽ đơn giản hơn rất nhiều khi bạn viết ra. Đặc biệt, nếu bạn trở thành một nhà văn giỏi, bạn có thể dễ dàng thể hiện bản thân và kết nối với mọi người. Điều đó sẽ nâng cao công việc, sự nghiệp của bạn theo những cách bạn không bao giờ tưởng tượng được.',NULL,NULL );
INSERT INTO `thongtin` VALUES('14','3',NULL,NULL,NULL,NULL,NULL,NULL,'4. Chú tâm','Hãy luôn là một người bình tĩnh và chú ý. Một người biết kiểm soát suy nghĩ và cảm xúc của chính mình. Một người luôn vững chắc như một tảng đá. Một người mà có thể khiến những người khác có thể tin tưởng và dựa vào.<br>Nhưng để đạt được sự bình tĩnh nội tâm đó đòi hỏi bạn phải tập luyện thật nhiều. Tôi không nghĩ chúng ta có thể hoàn toàn nắm vững kỹ năng này. Nhưng bằng cách thực hành kiểm soát những suy nghĩ của mình, bản thân chúng ta có thể trở nên tốt hơn. Một cách hay để kiểm soát suy nghĩ của bản thân là hãy luôn ở hiện tại. Khi bạn chú tâm đến hiện tại, mục tiêu không bao giờ bị lạc mất trong suy nghĩ. Nó luôn ở đó.',NULL,NULL);
INSERT INTO `thongtin` VALUES('15','3',NULL,NULL,NULL,NULL,NULL,NULL,'5. Hiệu suất',NULL,'../../image/langphi1.jpg','Hãy học cách làm việc để nhận được nhiều kết quả nhất trong khoảng thời gian ngắn nhất. Đó là mục tiêu cuối cùng của kỹ năng tạo năng suất và hiệu suất.');
INSERT INTO `thongtin` VALUES('16','3',NULL,NULL,NULL,NULL,NULL,NULL,'6. Kiên trì','Chắc hẳn bạn đã từng muốn từ bỏ một việc, một điều gì đó? Vậy thì chắc bạn cũng biết lý do tại sao? Bởi vì bản thân bạn không nhìn thấy bất kỳ kết quả nào của việc làm đó trong cuộc sống. Bạn cứ làm việc, làm việc, làm việc nhưng bạn không nhận được gì, không được mọi người công nhận, không được tiền, không được khen thưởng, chỉ có làm việc.<br>Nhưng nếu bạn không từ bỏ, cứ tiếp tục làm việc thì một ngày nào đó, bạn sẽ bắt đầu nhận được kết quả. Bạn thấy được mình đã làm tốt hơn, cảm thấy tự tin hơn, thậm chí kiếm nhiều tiền hơn. Còn nếu bạn không kiên trì, bạn sẽ không nhận được bất kỳ thứ gì trong số đó. Vì vậy, hãy phấn đấu để cái thiện và đừng bao giờ bỏ cuộc, quả ngọt sẽ đến với những người kiên trì.',NULL,NULL);
INSERT INTO `thongtin` VALUES('17','3',NULL,NULL,NULL,NULL,NULL,NULL,'7. Sở trường','Sự xuất sắc, sở trường của cá nhân cũng là một kỹ năng. Như Robert Greene, người đã mất 6 năm để viết lên một cuốn sách khác, Lebron James đã chơi trong mọi mùa giải trong sự nghiệp của mình. Hay Helen Keller đã xuất bản 5 cuốn sách, dù bà bị điếc và mù. Họ đều dùng sở trường của mình để khai thác tiềm năng, tạo ra thành công cho bản thân.<br>Hay với những người tầm thường quen thuộc hơn như nhân viên bán hàng top đầu trong bất kỳ công ty nào đều phải đến sớm và về muộn mỗi ngày. Hoặc người mẹ hy sinh các bữa tiệc đêm để nuôi dạy đứa con của mình bằng tất cả sự chú ý và tình yêu của cô ấy.<br>Điều đó được gọi là sở trường, điểm trội của họ.<br>Đừng bao giờ phân biệt những việc mà bạn làm. Hãy làm điều đó theo cách tốt nhất bạn có thể - xác định đã làm thì phải làm đến nơi đến chốn dù khó khăn đến đâu, còn nếu không thì tốt nhất không nên làm. Nếu bạn muốn khai thác và tận dụng toàn bộ tiềm năng của mình, trên đây là con đường nhanh nhất, nhưng nó cũng là con đường khó khăn nhiều chông gai nhất. Tuy nhiên trên con đường khám phá này, nó sẽ mang đến cho bạn nhiều ngạc nhiên và bất ngờ vượt ngoài mong đợi.',NULL,NULL);
INSERT INTO `thongtin` VALUES('18','4','Lịch sử AFF Cup ủng hộ Việt Nam: Philippines sở hữu thành tích toàn thua ở bán kết','Philippines đã vào bán kết AFF Cup 2018 sau khi giành một điểm trong trận hòa không bàn thắng trước Indonesia tối qua (25/11). Trong lịch sử, đội bóng có biệt danh "The Azkals" sở hữu thành tích toàn thua ở bán kết AFF Cup.','Nguyên Hoàng,','THEO NHỊP THÔNG TẤN XÃ VỈA HÈ',NULL,'Công Phượng vào bếp, đeo tạp dề học làm bánh',NULL,'Bóng đá Philippines đã có những tiến bộ vượt bậc trong khoảng 8 năm trở lại đây. Từ năm 2010 đến 2014, đội tuyển bóng đá nước này đã có 3 lần liên tiếp lọt vào bán kết AFF Cup. Tuy nhiên, họ lại chưa từng một lần giành chiến thắng để góp mặt trong trận đấu tranh ngôi vương.<br>AFF Cup 2010 được coi là bước đột phá với đội tuyển có biệt danh "The Azkals". Ở vòng bảng, họ bất ngờ quật ngã đương kim vô địch Việt Nam 2 bàn không gỡ ngay trên sân Mỹ Đình, sau đó tiến vào bán kết với vị trí nhì bảng B. Tại đây, họ bị Indonesia đánh bại với tỷ số tối thiểu 1-0 ở cả 2 lượt trận.<br>2 năm sau, Philippines tiếp tục lọt vào vòng bán kết với vị trí nhì bảng. Tại đây, Phil Younghusband và các đồng đội đã thi đấu cực hay và chỉ chịu thất bại với tổng tỷ số 0-1 trước nhà vô địch năm đó là Singapore.','../../image/philippin1.jpg',NULL );
INSERT INTO `thongtin` VALUES('19','4'NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Đến AFF Cup 2014, Philippines lột xác hoàn toàn khi trình diễn lối chơi tấn công như vũ bão. Họ ghi nhiều bàn thắng nhất vòng bảng (9 bàn). Đáng tiếc, đối thủ của Philippines tại bán kết lại là Thái Lan, một đội bóng quá mạnh ở thời điểm ấy. Dù tạo nên đôi chút bất ngờ khi cầm hòa nhà vô địch năm đó với tỷ số 0-0 trên sân nhà , thế nhưng khi phải làm khách trên sân của "Voi chiến", Philippines nhanh chóng sụp đổ khi để thua 3 bàn không gỡ.<br>Năm 2018, thật trùng hợp khi Philippines lại tiến vào bán kết với ngôi nhì bảng. Đối thủ của họ là đội tuyển Việt Nam. Đội bóng của HLV Park Hang-seo đang có phong độ rất tốt với thành tích bất bại sau vòng bảng. Liệu rằng đoàn quân của HLV Eriksson có thay đổi được lịch sử? Câu trả lời sẽ có sau ngày 6/12 tới.<br>Lịch thi đấu bán kết AFF Cup 2018<br>Lượt đi:<br>1/12/2018: Malaysia vs Thái Lan<br>2/12/2018: Philippines vs Việt Nam<br>Lượt về:<br>5/12/2018: Thái Lan vs Malaysia<br>6/12/2018: Việt Nam vs Philippines',NULL,NULL);
INSERT INTO `thongtin` VALUES('20','5','Sau màn ra mắt ấn tượng tại Hà Nội, VinFast tiếp tục thu hút hàng nghìn người dân tới tham quan và đặt mua tại Sài Gòn','Cũng như Hà Nội, người Sài Gòn rất thích thú khi được tận mắt chiêm ngưỡng 3 dòng xe ô tô, xe máy sang trọng của tập đoàn Vingroup. Rất nhiều người đã đặt cọc mua xe ô tô VinFast và xe máy điện thông minh Klara để ủng hộ hàng Việt Nam.','Nguyên Hoàng,','THEO NHỊP THÔNG TẤN XÃ VỈA HÈ',NULL,'Mừng sinh nhật 4 tuổi, siêu thị VinMart "chơi lớn" tặng ô tô VinFast tri ân khách hàng tại tòa nhà LandMark 81',NULL,'Sau màn ra mắt ấn tượng tại Hà Nội, VinFast tiếp tục thu hút hàng nghìn người dân tới tham quan và đặt mua tại Sài Gòn.Thực hiện: Kingpro Sáng ngày 26/11, tại Vincom Landmark 81 (quận Bình Thạnh, TP. HCM) đã diễn ra sự kiện ra mắt, mở bán và nhận đặt xe ô tô VinFast và xe máy điện thông minh Klara . Đây là lễ ra mắt xe VinFast dành cho người dân ở Sài Gòn sau khi đã ra mắt trước đó tại Hà Nội (ngày 20/11).<br>Theo ghi nhận, mặc dù 10h sự kiện mới bắt đầu nhưng nhiều người đã có mặt từ khá sớm để chờ đợi được chiêm ngưỡng những chiếc ô tô VinFast, xe máy Klara sang trọng.<br>Trước đó 1 ngày, sự kiện bị hoãn do trời mưa bão (bão số 9) khiến nhiều người tiếc nuối. Tuy nhiên đến hôm nay người Sài Gòn đã thật sự rất thoả mãn khi lần đầu được thấy tận mắt chiếc ô tô và xe máy mang thương hiệu Việt Nam.','../../image/vinfast1.jpg','Mẫu xe VinFast Lux SA 2.0 được trưng bày thu hút nhiều người quan tâm.');
INSERT INTO `thongtin` VALUES('21','5',NULL,NULL,NULL,NULL,NULL,'VinFast nói là làm: Đã có điểm sạc xe máy điện Klara tại hệ thống Vinmart+, hoàn toàn miễn phí',NULL,NULL,'../../image/vinfast2.jpg','Lux A 2.0 cũng tương tự.');
INSERT INTO `thongtin` VALUES('22','5',NULL,NULL,NULL,NULL,NULL,'Câu chuyện phía sau cơn sốt xe VinFast: Hàng Việt Nam thực sự đã chinh phục được người Việt Nam!',NULL,'"Thật tự hào vì đây là sản phẩm do người Việt mình sản xuất, tôi vui lắm nên đến đây từ sớm để chờ vào xem cho đã mắt. Chúc mừng tập đoàn Vingroup đã có một bước tiến mới trong việc phát triển công nghệ ô tô", anh Vương (quận Bình Thạnh) vui vẻ cho chia sẻ.<br>Không khí tham quan, đặt cọc ô tô VinFast và trải nghiệm xe máy điện Klara rất nhộn nhịp dù sự kiện diễn ra trong nhà, thay vì ngoài trời như dự kiến trước đó.<br>Hàng trăm người và hầu hết đều đánh giá ô tô VinFast và xe máy điện Klara rất đẹp và giá cả hợp lý. Vì vậy, tại khu vực đăng ký đặt cọc để mua xe ô tô đã chật kín, nhân viên không kịp làm thủ tục cho khách mua xe.',NULL,NULL);
INSERT INTO `thongtin` VALUES('23','6','Thương hiệu đồng hồ Franck Muller chính thức có mặt tại Việt Nam','Thương hiệu đồng hồ Franck Muller được thành lập bởi nghệ nhân Franck Muller cùng doanh nhân Vartan Sirmakes đã chính thức có mặt tại Việt Nam và được phân phối chính hãng bởi S&S Knightsbridge Việt Nam.','Nguyên Hoàng,','THEO NHỊP THÔNG TẤN XÃ VỈA HÈ',NULL,NULL,NULL,'Thương hiệu Franck Muller ra đời năm 1991 ở quê hương Geneva từ mối nhân duyên của nghệ nhân Franck Muller và doanh nhân - nhà chế tác vỏ đồng hồ Vartan Sirmakes. Sự kết hợp giữa hai tài năng đưa cái tên Franck Muller nổi danh về những cỗ máy siêu phức tạp như Revolution 3 - Tourbillon Triple-Axis đầu tiên trên thế giới hay Giga Tourbillon – Tourbillon lớn nhất thế giới, bên cạnh những bộ sưu tập dáng vỏ Cintrée Curvex độc đáo kết hợp cùng nghệ thuật kim hoàn quyến rũ.<br>Theo học 4 năm tại Geneva School of Watch Making (trường dạy chế tác đồng hồ Geneva), Franck đã nhanh chóng gây dựng được tên tuổi của mình với tài năng thiên bẩm về kĩ thuật, nhiều nhà đấu giá cũng như các nhà sưu tầm đồng hồ trên khắp thế giới đã gửi những chiếc đồng hồ quý giá của họ cho Franck để phục hồi và sửa chữa, đặc biệt có cả những chiếc đồng hồ được trưng bày tại bảo tàng Patek Philippe.','../../image/dongho1.jpg','thu hút nhiều người quan tâm');
INSERT INTO `thongtin` VALUES('24','6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sau vài năm khôi phục những bộ chuyển động tinh vi, Franck bắt đầu vận dụng những kĩ thuật của đồng hồ đeo tay và đồng hồ bỏ túi siêu phức tạp để tạo nên những chiếc đồng hồ độc nhất mang tên mình. Năm 1983, chiếc đồng hồ đeo tay đầu tiên mang tên Franck Muller ra đời, và ngay lập tức ông trở thành nghệ nhân độc lập yêu thích của giới sưu tập tinh hoa. Mỗi năm, Franck lại trình làng một mẫu World Premier (các mẫu đồng hồ lần đầu tiên xuất hiện trên thế giới), kết hợp những tính năng phức tạp chưa từng được chế tạo trước đó.<br>Franck Muller Aeternitas Mega được biết đến là chiếc đồng hồ đeo tay phức tạp nhất thế giới với 36 tính năng, trong đó bao gồm nhiều tính năng siêu phức tạp được cấu thành từ 1,483 bộ phận và được sản xuất hoàn toàn khép kín. Thiết kế mới mang tính cách mạng này và những phiên bản Grand Complications tiếp theo đã trở thành nền tảng, đưa cái tên Franck Muller gắn liền với danh hiệu “Master of Complications” - Bậc thầy của những cố máy phức tạp.',NULL,NULL);